#!/usr/bin/env bash

# *very* loosely based on https://github.com/nawar/kodi-cli
# RPC defined in https://kodi.wiki/view/JSON-RPC_API/v12

cleanup() {
	local i rc=$?

	while read -r i; do
		eval ${CLEANUP[i]}
	done < <(printf "%s\n" "${!CLEANUP[@]}" | tac)

	return $rc
}

error() {
	printf "ERROR: %s\n" "$@" >&2
	exit 1
}

req() {
	local method="$1" params="" param req filter=( cat )
	shift
	while (($# >= 2)); do
		params="${params:+$params, }\"$1\": $2"
		shift 2
	done
	if (( $# > 0 )); then
		filter=( jq -r "if ((.result$1) != null) then .result$1 else . | halt_error end" )
	fi
	req='{"jsonrpc": "2.0", "id": 0, "method": '"\"$method\"${params:+, \"params\": { "$params" \}}}"
	: echo "$req"
	curl -s -X POST --header "Content-Type: application/json" \
			"http://$KODI_URI/jsonrpc" -d "$req" \
		| tee \
		| "${filter[@]}"
}

reqok() {
	req "$@" '== "OK" // null' >/dev/null
}

init() {
	local IFS=$'\n' host port user pass media_prefix _

	[[ -n "$KODI_URI" ]] && return
	[[ -f "$HOME/.kodirc" ]] || error "no \$KODI_URI or ~/.kodirc"
	CLEANUP=( )
	trap cleanup EXIT

	read -r -d '' host port user pass media_prefix _ < "$HOME/.kodirc"
	KODI_URI="$user:$pass@$host:$port"
	MEDIA_PREFIX="$media_prefix"
}

play_pause() {
	local action="$1"
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	# drop stdout to /dev/null unless verbose (will show fadeout %)
	if [ -z "$VERBOSE" ]; then
		exec 1>/dev/null
	fi

	if ! req Player.PlayPause playerid "$player" ${action:+play "$action"} '.speed' 2>&1; then
		if [[ "$action" == true ]]; then
			# just play whatever we can finid...
			reqok Player.Open item '{"playlistid": 0, "position": 0}' \
				|| error "Could not resume"
		else
			error "Could not pause"
		fi
	fi
}

play() {
	play_pause true
}

pause() {
	play_pause false
}

fadeout() {
	local vol

	# drop stdout to /dev/null unless verbose (will show fadeout %)
	if [ -z "$VERBOSE" ]; then
		exec 1>/dev/null
	fi

	# try to pause even if something errored out...
	# but cleanup is executed in reverse order so
	# fiddle with indices to pause before restoring volume
	CLEANUP[11]="echo 'Pausing...'; pause"

	vol=$(req Application.GetProperties "properties" '["volume"]' .volume) \
		|| error "Could not get initial volume"
	CLEANUP[10]="req Application.SetVolume volume $vol ''"

	# set volume to 0 and pause. cleanup will restore volume after pause.
	while (( vol-- > 0 )); do
		req Application.SetVolume volume $vol "" \
			|| error "Could not lower volume to $vol"
		sleep 2
	done
}

repeat() {
	local action=${1:-all} # off one all
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	local repeat
	repeat=$(req Player.GetProperties playerid "$player" properties '["repeat"]' '.repeat') \
		|| error "Could not get player repeat state"
	if [[ "$repeat" == "$action" ]]; then
		echo "OK already"
		return
	fi

	req Player.SetRepeat playerid "$player" repeat "\"$action\"" "" \
		|| error "Could not set repeat $action"
}

shuffle() {
	local action=${1:-true} # true false \"toggle\"
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	local shuffled
	shuffled=$(req Player.GetProperties playerid "$player" properties '["shuffled"]' '.shuffled') \
		|| error "Could not get player shuffled state"
	if [[ "$shuffled" == "$action" ]]; then
		echo "OK already"
		return
	fi

	req Player.SetShuffle playerid "$player" shuffle "$action" "" \
		|| error "Could not set shuffle $action"
}
random() { shuffle "$@"; }

playlist_add() {
	# XXX better argument parsing:
	# - format (audio/video/picture)
	# - append or replace playlist
	# - search instead of assume directory? not recursive?
	# appends to audio playlist
	local format=audio
	local action=append
	local folder="$1"
	case "$folder" in
	/*) ;;
	*) folder="$MEDIA_PREFIX/$folder";;
	esac

	local playlistid
	playlistid=$(req Playlist.GetPlaylists ' | .[] | select(.type == "'"$format"'").playlistid') \
		|| error "Could not find playlist for $format"

	case "$action" in
	append) ;;
	replace) req Playlist.clear playlistid "$playlistid" || error "Couldn't clear playlist";;
	*) error "Unhandled action $action";;
	esac

	reqok Playlist.add playlistid "$playlistid" item '{"directory": "'"$folder"'", "recursive": true}' \
		|| error "Couldn't add $folder to playlist"

	reqok Player.Open item '{"playlistid": '"$playlistid"', "position": 0}' \
		|| error "Couldn't play newly edited playlist"

	# kodi won't remember repeat, force it here...
	repeat

	echo "Added $folder"
}

playlist() {
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	local playlistid
	playlistid=$(req Player.GetProperties playerid "$player" properties '["playlistid"]' .playlistid) \
		|| error "Could not find active playlist"

	req Playlist.GetItems playlistid "$playlistid" ''
}

volume() {
	local val="$1" # percent, "increment", "decrement"

	case "$val" in
	up) val='"increment"';;
	down) val='"decrement"';;
	esac

	req Application.SetVolume volume "$val" ''
}
vol() { volume "$@"; }

goto() {
	local to="$1" # number, "next", "previous"

	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	reqok Player.GoTo playerid "$player" to "$to"
}
next() {
	goto '"next"'
}

prev() {
	# Player.GoTo has a previous option, but that doesn't seem to work well?
	# Instead get current position in playlist and GoTo it.
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	local playlistid
	playlistid=$(req Player.GetProperties playerid "$player" properties '["playlistid"]' .playlistid) \
		|| error "Could not find active playlist"
	local position
	position=$(req Player.GetProperties playerid "$player" properties '["position"]' .position) \
		|| error "Could not find active playlist position"
	
	if (( position == 0 )); then
		position=$(req Playlist.GetProperties playlistid "$playlistid" properties '["size"]' .size) \
			|| error "Could not get playlist size"
	fi

	reqok Player.GoTo playerid "$player" to "$((position - 1))"
}

find() {
	local search="$1"

	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	local playlistid
	playlistid=$(req Player.GetProperties playerid "$player" properties '["playlistid"]' .playlistid) \
		|| error "Could not find active playlist"

	local index
	index=$(req Playlist.GetItems playlistid 0 '.items | map(.label | contains("'"$search"'")) | index(true)') \
		|| error "Could not find $search"

	reqok Player.GoTo playerid "$player" to "$index"
}

seek() {
	local pos="$1"

	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	case "$pos" in
	*%)
		# jump to %
		pos='{"percentage": '"${pos%'%'}"'}';;
	+*|-*)

		pos='{"seconds": '"${pos#+}"'}'
		;;
	*:*)
		local hour min sec
		sec="${pos##*:}"
		min="${pos%:*}"
		hour="${min%:*}"
		[[ "$hour" = "$min" ]] && hour=0
		min="${min##*:}"
		[[ "$hour" = "${hour%:*}" ]] || error "Only up to hour:min:sec"
		pos='{"time": {"hours": '"$hour"', "minutes": '"$min"', "seconds": '"$sec"'}}'
		;;
	*)
		local hour min sec
		hour=$((pos/3600))
		min=$((pos/60 % 60))
		sec=$((pos % 60))
		pos='{"time": {"hours": '"$hour"', "minutes": '"$min"', "seconds": '"$sec"'}}'
		;;
	esac

	req Player.Seek playerid "$player" value "$pos" ''
}

status() {
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	local label file
	label=$(req Player.GetItem playerid "$player" .item.label) || label="UNKNOWN"
	file=$(req Player.GetItem playerid "$player" properties '["file"]' .item.file) || file="UNKNOWN"
	file="${file#$MEDIA_PREFIX}"

	local props
	local speed shuffled repeat playlistid position percentage
	local time time_hour time_min time_sec time_milli
	local ttime ttime_hour ttime_min ttime_sec ttime_milli
	props=$(req Player.GetProperties playerid "$player" \
			properties '["speed", "shuffled", "repeat", "playlistid", "position", "percentage", "time", "totaltime"]' \
			' | "\(.speed) \(.shuffled) \(.repeat) \(.playlistid) \(.position) \(.percentage) " +
			    "\(.time | "\(.hours) \(.minutes) \(.seconds) \(.milliseconds)") " +
			    "\(.totaltime | "\(.hours) \(.minutes) \(.seconds) \(.milliseconds)")"'
		) || error "Could not get player properties"
	read -r speed shuffled repeat playlistid position percentage \
		time_hour time_min time_sec time_milli \
		ttime_hour ttime_min ttime_sec ttime_milli <<<"$props"
	printf -v time "%d:%02d:%02d.%03d" "$time_hour" "$time_min" "$time_sec" "$time_milli" \
		|| error "time not well formated: $props"
	printf -v ttime "%d:%02d:%02d.%03d" "$ttime_hour" "$ttime_min" "$ttime_sec" "$ttime_milli"
	case "$speed" in
	0) speed="Paused";;
	1) speed="Playing";;
	*) speed="Playing (speed: $speed)";;
	esac

	local volume muted
	props=$(req Application.GetProperties \
			properties '["volume", "muted"]' \
			' | "\(.volume) \(.muted)"'
		) || error "Could not get application properties"
	read -r volume muted <<<"$props"
	case "$muted" in
	true) volume="$volume (Muted)";;
	esac

	cat <<EOF
State: $speed
Current: $label
$file
Position: $time / $ttime (${percentage:0:5}%)
Playlist: $playlistid (track n° $position)
Shuffled: $shuffled
Repeat: $repeat
Volume: $volume
EOF
}

help() {
	cat <<EOF
Run commands e.g. $0 play

Available commands:
  play_pause (toggles)
  play
  pause
  repeat [all|one|off]
EOF
}

init

"$@"
