#!/usr/bin/env bash

# *very* loosely based on https://github.com/nawar/kodi-cli
# RPC defined in https://kodi.wiki/view/JSON-RPC_API/v12

cleanup() {
	local i rc=$?

	while read -r i; do
		eval ${CLEANUP[i]}
	done < <(printf "%s\n" "${!CLEANUP[@]}" | tac)

	return $rc
}

error() {
	printf "ERROR: %s\n" "$@" >&2
	exit 1
}

req() {
	local method="$1" params="" param req filter=( cat )
	shift
	while (($# >= 2)); do
		params="${params:+$params, }\"$1\": $2"
		shift 2
	done
	if (( $# > 0 )); then
		filter=( jq -r "if ((.result$1) != null) then .result$1 else . | halt_error end" )
	fi
	req='{"jsonrpc": "2.0", "id": 0, "method": '"\"$method\"${params:+, \"params\": { "$params" \}}}"
	: echo "$req"
	curl -s -X POST --header "Content-Type: application/json" \
			"http://$KODI_URI/jsonrpc" -d "$req" \
		| tee \
		| "${filter[@]}"
}

reqok() {
	req "$@" '== "OK" // null' >/dev/null
}

init() {
	local IFS=$'\n' host port user pass media_prefix _

	[[ -n "$KODI_URI" ]] && return
	[[ -f "$HOME/.kodirc" ]] || error "no \$KODI_URI or ~/.kodirc"
	CLEANUP=( )
	trap cleanup EXIT

	read -r -d '' host port user pass media_prefix _ < "$HOME/.kodirc"
	KODI_URI="$user:$pass@$host:$port"
	MEDIA_PREFIX="$media_prefix"
}

play_pause() {
	local action="$1"
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	req Player.PlayPause playerid "$player" ${action:+play "$action"} '.speed' \
		|| error "Could not play/pause"
}

play() {
	play_pause true
}

pause() {
	play_pause false
}

fadeout() {
	local vol

	# drop stdout to /dev/null unless verbose (will show fadeout %)
	if [ -z "$VERBOSE" ]; then
		exec 1>/dev/null
	fi

	# try to pause even if something errored out...
	# but cleanup is executed in reverse order so
	# fiddle with indices to pause before restoring volume
	CLEANUP[11]="echo 'Pausing...'; pause"

	vol=$(req Application.GetProperties "properties" '["volume"]' .volume) \
		|| error "Could not get initial volume"
	CLEANUP[10]="req Application.SetVolume volume $vol ''"

	# set volume to 0 and pause. cleanup will restore volume after pause.
	while (( vol-- > 0 )); do
		req Application.SetVolume volume $vol "" \
			|| error "Could not lower volume to $vol"
		sleep 2
	done
}

repeat() {
	local action=${1:-all} # off one all
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	local repeat
	repeat=$(req Player.GetProperties playerid "$player" properties '["repeat"]' '.repeat') \
		|| error "Could not get player repeat state"
	if [[ "$repeat" == "$action" ]]; then
		echo "OK already"
		return
	fi

	req Player.SetRepeat playerid "$player" repeat "\"$action\"" "" \
		|| error "Could not set repeat $action"
}

shuffle() {
	local action=${1:-true} # true false \"toggle\"
	local player
	player=$(req Player.GetActivePlayers '[0].playerid') \
		|| error "No active player"

	local shuffled
	shuffled=$(req Player.GetProperties playerid "$player" properties '["shuffled"]' '.shuffled') \
		|| error "Could not get player shuffled state"
	if [[ "$shuffled" == "$action" ]]; then
		echo "OK already"
		return
	fi

	req Player.SetShuffle playerid "$player" shuffle "$action" "" \
		|| error "Could not set shuffle $action"
}
random() { shuffle "$@"; }

playlist_add() {
	# XXX better argument parsing:
	# - format (audio/video/picture)
	# - append or replace playlist
	# - search instead of assume directory? not recursive?
	# appends to audio playlist
	local format=audio
	local action=append
	local folder="$1"
	case "$folder" in
	/*) ;;
	*) folder="$MEDIA_PREFIX/$folder";;
	esac

	local playlistid
	playlistid=$(req Playlist.GetPlaylists ' | .[] | select(.type == "'"$format"'").playlistid') \
		|| error "Could not find playlist for $format"

	case "$action" in
	append) ;;
	replace) req Playlist.clear playlistid "$playlistid" || error "Couldn't clear playlist";;
	*) error "Unhandled action $action";;
	esac

	reqok Playlist.add playlistid "$playlistid" item '{"directory": "'"$folder"'", "recursive": true}' \
		|| error "Couldn't add $folder to playlist"

	reqok Player.Open item '{"playlistid": '"$playlistid"', "position": 0}' \
		|| error "Couldn't play newly edited playlist"

	echo "Added $folder"
}

playlist() {
	# XXX better argument parsing:
	# - format (audio/video/picture)
	local format=audio
	local playlistid
	playlistid=$(req Playlist.GetPlaylists ' | .[] | select(.type == "'"$format"'").playlistid') \
		|| error "Could not find playlist for $format"

	req Playlist.GetItems playlistid "$playlistid" ''
}

help() {
	cat <<EOF
Run commands e.g. $0 play

Available commands:
  play_pause (toggles)
  play
  pause
  repeat [all|one|off]
EOF
}

init

"$@"
